{
 "cells": [
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# Sampling origins across different cities and creating origin-destination pairs.\n",
    "\n",
    "## Prerequisites\n",
    "This repository builds on the python package OSMNx (v.2.0.1, https://osmnx.readthedocs.io/en/stable/). I recommend installing it via conda:\n",
    "```\n",
    "conda create -n ox -c conda-forge --strict-channel-priority osmnx\n",
    "```\n",
    "For sampling nodes based on city names two additional packages are required, namely geopy (v.2.3.1, https://geopy.readthedocs.io/en/stable/) and overpy (v.0.7, https://python-overpy.readthedocs.io/en/latest/)\n",
    "\n",
    "```\n",
    "pip install geopy\n",
    "pip install overpy nodes run Ubuntu Jammy 22.04 LTS.\n",
    "There is local scratch space on each node, which is shared between the jobs currently running. Connected to Kebnekaise is also our parallel file system Ransarn (where your project storage is located), which provide quick access to files regardless of which node they run on. For more information about the different file systems that are available on our systems, read the Filesystems and Storage page.\n",
    "```\n",
    "\n",
    "For visualizing routes and geometry on maps I use the folium package (v.0.19.4, https://python-visualization.github.io/folium/latest/) that is included in the OSMNx package, but for creating static images of these visualizations the Selenium package is required (v.4.28.0, https://www.selenium.dev/documentation/)\n",
    "\n",
    "```\n",
    "pip install selenium\n",
    "```\n",
    "\n",
    "## This exampleCities are used as the basis to find random samples of intersections. The region and country names are nice to have, but they are not necessary."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "sample_size = 3\n",
    "min_distance = 3\n",
    "random_seed = 3\n",
    "network_type = 'drive'\n",
    "point_distance_size = 10000\n",
    "experiment_name = \"2025-03-A\"\n",
    "base_path=f\"/proj/nobackup/streetnetwork-alignment/{experiment_name}\"\n",
    "min_od_distance = 4750\n",
    "max_od_distance = 5250\n",
    "sample_size = 144\n",
    "import os\n",
    "\n",
    "if not os.path.exists(base_path):\n",
    "    os.makedirs(base_path)\n",
    "    \n",
    "parameters_file_path = os.path.join(base_path, f\"{experiment_name}_parameters.csv\")\n",
    "city_sample_nodes_path = os.path.join(base_path, f'city_sample_nodes_{experiment_name}.csv')\n",
    "local_graph_folder = os.path.join(base_path,'local_origin_graphs')\n",
    "import csv\n",
    "\n",
    "with open(parameters_file_path, mode='w', newline='') as file:\n",
    "    writer = csv.writer(file)\n",
    "    writer.writerow([\"Parameter\", \"Value\"])\n",
    "    writer.writerow([\"sample_size\", sample_size])\n",
    "    writer.writerow([\"min_distance\", min_distance])\n",
    "    writer.writerow([\"random_seed\", random_seed])\n",
    "    writer.writerow([\"network_type\", network_type])\n",
    "    writer.writerow([\"point_distance_size\", point_distance_size])\n",
    "    writer.writerow([\"min_od_distance\", min_od_distance])\n",
    "    writer.writerow([\"max_od_distance\", max_od_distance])\n",
    "    writer.writerow([\"base_path\", base_path])\n",
    "    writer.writerow([\"city_sample_nodes_path\", city_sample_nodes_path])\n",
    "    writer.writerow([\"local_graph_folder\", local_graph_folder])\n",
    "    writer.writerow([\"base_path\", base_path])\n",
    "    writer.writerow([\"experiment_name\", experiment_name])\n",
    "\n",
    "import pandas as pd\n",
    "param = pd.read_csv(parameters_file_path)\n",
    "display(param)\n",
    "\n",
    "import multiprocessing\n",
    "\n",
    "num_processes = multiprocessing.cpu_count()  # Adjust based on your system's capabilities\n",
    "print(f\"Number of processes to use: {num_processes}\")\n",
    "\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "# The workflow for analyzing the routes begins with coordinate points used as origin locations.\n",
    "import pandas as pd\n",
    "\n",
    "df = pd.read_csv(\"100_city_sample.csv\")\n",
    "display(df)\n",
    "\n",
    "\n",
    "# To sample nodes from the cities we call use a method from sample_nodes.py\n",
    "import node_sampling\n",
    "\n",
    "df = node_sampling.get_random_nodes_for_all_cities(df,min_distance_km=min_distance,sample_size=sample_size,random_seed=random_seed)\n",
    "\n",
    "\n",
    "display(df)\n",
    "\n",
    "import os # for file operations\n",
    "city_sample_nodes_path = os.path.join(base_path, f'city_sample_nodes_{experiment_name}.csv')\n",
    "df.to_csv(os.path.join(base_path,city_sample_nodes_path))\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "from origin_graph import origin_graph  # for creating the origin graph object\n",
    "import os  # for file operations\n",
    "import ast  # for parsing string to tuple\n",
    "import pandas as pd  # for reading the csv file\n",
    "import osmnx as ox  # for plotting the graph\n",
    "import matplotlib.pyplot as plt  # for plotting the graphs\n",
    "import multiprocessing\n",
    "import logging\n",
    "logging.basicConfig(level=logging.ERROR, format='%(asctime)s - %(levelname)s - %(message)s',filename='jupyter.log', filemode='w')\n",
    "\n",
    "\n",
    "sub_folder = \"local_origin_graphs\"\n",
    "local_graph_folder = os.path.join(base_path, sub_folder)\n",
    "if not os.path.exists(local_graph_folder):\n",
    "    os.makedirs(local_graph_folder)\n",
    "\n",
    "print(city_sample_nodes_path)\n",
    "df = pd.read_csv(city_sample_nodes_path)\n",
    "\n",
    "def process_row(row):\n",
    "    if os.path.exists(row['graph_path']):\n",
    "        #print(f\"Graph exists: {row['graph_path']}\")\n",
    "        return f\"Graph already exists {row['graph_path']}\"\n",
    "    else:\n",
    "        print(f\"---Graph missing: {row['graph_path']}---\")\n",
    "        # Apply the function asynchronously\n",
    "    try:\n",
    "        latlon_point = ast.literal_eval(row['node_latlon'])\n",
    "        og = origin_graph(origin_point=latlon_point, distance_from_point=point_distance_size,\n",
    "                          city_name=row[\"city_name\"], network_type=network_type, remove_parallel=True, simplify=True)\n",
    "    \n",
    "        og.save_graph(row['graph_path'])\n",
    "    \n",
    "        # Plot the origin graph to see if something is obviously wrong\n",
    "        ox.plot_graph(og.graph, node_color='blue', node_size=10, edge_linewidth=1, edge_color='black', bgcolor='white',\n",
    "                       save=True, filepath=os.path.join(local_graph_folder, f\"{row['city_name']}_{row['node_id']}.png\"), show=False)\n",
    "        logging.error(f\"Finished with graph: {row['graph_path']}\")\n",
    "        return f\"Finished with graph: {row['graph_path']}\"\n",
    "\n",
    "    except Exception as e:\n",
    "        logging.error(f\"error {e} creating {row['graph_path']}\")\n",
    "        return f\"Failed with graph: {row['graph_path']} error {e}\"\n",
    "        \n",
    "num_processes = multiprocessing.cpu_count()  # Adjust based on your system's capabilities\n",
    "print(f\"Number of processes to use: {num_processes}\")\n",
    "\n",
    "# Collect results from multiprocessing\n",
    "try:\n",
    "    # Use multiprocessing Pool for parallel processing\n",
    "    with multiprocessing.Pool(processes=num_processes) as pool:\n",
    "        # Use pool.map instead of apply_async for better control and result handling\n",
    "        results = pool.map(process_row, [row for _, row in df.iterrows()])\n",
    "    \n",
    "    # Optional: Process and log the results\n",
    "    for result in results:\n",
    "        print(result)\n",
    "\n",
    "except Exception as e:\n",
    "    logging.error(f\"Multiprocessing error: {e}\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "import pandas as pd \n",
    "import os \n",
    "df = pd.read_csv(city_sample_nodes_path)\n",
    "\n",
    "for index, row in df.iterrows():\n",
    "        if os.path.exists(row['graph_path']):\n",
    "            #print(f\"Graph exists: {row['city_name']}_{row['node_id']}\")\n",
    "            continue\n",
    "        else:\n",
    "            print(row['node_id'])\n",
    "            print(f\"---Graph missing: {row['graph_path']}---\")\n",
    "\n",
    "\n",
    "print(df[\"graph_path\"][0])"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "import pandas as pd\n",
    "local_graph_folder = os.path.join(base_path, \"local_origin_graphs\")\n",
    "df = pd.read_csv(city_sample_nodes_path)\n",
    "df['graph_path'] = df.apply(lambda row: os.path.join(local_graph_folder, f\"{row['city_name']}_{row['node_id']}.graphml\"), axis=1)\n",
    "df['random_seed'] = random_seed\n",
    "df['min_distance'] = min_distance\n",
    "df['point_distance_size'] = point_distance_size\n",
    "display(df)\n",
    "df.to_csv(city_sample_nodes_path, index=False)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "import os\n",
    "import joblib\n",
    "num_processes = joblib.cpu_count()\n",
    "print(f\"Number of processes to use: {num_processes}\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {
    "scrolled": true
   },
   "outputs": [],
   "source": [
    "# The next step is to add weights to the edges of the graph.\n",
    "from origin_graph import origin_graph # for creating the origin graph object\n",
    "import pandas as pd # for reading the csv file\n",
    "import joblib # replacing multiprocessing with joblib\n",
    "\n",
    "df = pd.read_csv(city_sample_nodes_path)\n",
    "\n",
    "if 'weights_added' not in df.columns:\n",
    "    df['weights_added'] = None\n",
    "\n",
    "def add_graph_weights(row):\n",
    "    try:\n",
    "        og = origin_graph.from_graphml(graphml_path=row['graph_path'])\n",
    "        og.add_simplest_paths_from_origin()\n",
    "        og.add_weights('deviation_from_prototypical')\n",
    "        og.add_weights('node_degree')\n",
    "        og.add_weights('instruction_equivalent')\n",
    "        og.save_graph(row['graph_path'])\n",
    "        print(f\"Finished with graph: {row['city_name']} node: {row['node_id']}\")\n",
    "        return True,row['city_name'],row['node_id']\n",
    "    except Exception as e:\n",
    "        print(f\"Failed with graph: {row['graph_path']} error {e}\")\n",
    "        return False,row['city_name'],row['node_id']\n",
    "\n",
    "# Number of processes to use\n",
    "num_processes = joblib.cpu_count()\n",
    "print(f\"Number of processes to use: {num_processes}\")\n",
    "\n",
    "# Collect results from joblib\n",
    "try:\n",
    "    # Use joblib's Parallel and delayed for parallel processing\n",
    "    results = joblib.Parallel(n_jobs=num_processes,backend='loky')(\n",
    "        joblib.delayed(add_graph_weights)(row) for _, row in df.iterrows()\n",
    "    )\n",
    "    for result in results:\n",
    "        if result[0]:  # Check if the value in results[0] is True\n",
    "            # Find the row in df where both 'city_name' and 'start_node' match\n",
    "            mask = (df['city_name'] == result[1]) & (df['start_node'] == result[2])\n",
    "            df.loc[mask, 'weights_added'] = True  # Update 'weights_added' to True\n",
    "\n",
    "\n",
    "except Exception as e:\n",
    "    logging.error(f\"Joblib parallel processing error: {e}\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "metadata": {
    "scrolled": true
   },
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "odpair data will be stored at /proj/nobackup/streetnetwork-alignment/2025-03-A/od_pair_data\n",
      "Number of processes to use: 63\n",
      "Finished finding OD_pairs for graph: Copenhagen node: 272274819\n",
      "Finished finding OD_pairs for graph: Dubai node: 12504312388\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "/hpc2n/eb/software/Python-bundle-PyPI/2023.10-GCCcore-13.2.0/lib/python3.11/site-packages/joblib/externals/loky/process_executor.py:752: UserWarning: A worker stopped while some jobs were given to the executor. This can be caused by a too short worker timeout or by a memory leak.\n",
      "  warnings.warn(\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Finished finding OD_pairs for graph: Beijing node: 4571627076\n",
      "Finished finding OD_pairs for graph: Dubai node: 1039038802\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "/pfs/stor10/users/home/a/arvidh/Documents/perceived-route-complexity/alignment.py:74: RuntimeWarning: divide by zero encountered in divide\n",
      "  normalized_circ_cross_corr = circ_cross_corr / np.max(circ_cross_corr)\n",
      "/pfs/stor10/users/home/a/arvidh/Documents/perceived-route-complexity/alignment.py:74: RuntimeWarning: invalid value encountered in divide\n",
      "  normalized_circ_cross_corr = circ_cross_corr / np.max(circ_cross_corr)\n",
      "/pfs/stor10/users/home/a/arvidh/Documents/perceived-route-complexity/alignment.py:74: RuntimeWarning: divide by zero encountered in divide\n",
      "  normalized_circ_cross_corr = circ_cross_corr / np.max(circ_cross_corr)\n",
      "/pfs/stor10/users/home/a/arvidh/Documents/perceived-route-complexity/alignment.py:74: RuntimeWarning: invalid value encountered in divide\n",
      "  normalized_circ_cross_corr = circ_cross_corr / np.max(circ_cross_corr)\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Failed finding OD_pairs for  graph: /proj/nobackup/streetnetwork-alignment/2025-03-A/local_origin_graphs/Damascus_1566546477.graphml error 'origin_graph' object has no attribute 'od_pairs'\n",
      "Finished finding OD_pairs for graph: Detroit node: 62679624\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "/pfs/stor10/users/home/a/arvidh/Documents/perceived-route-complexity/alignment.py:74: RuntimeWarning: divide by zero encountered in divide\n",
      "  normalized_circ_cross_corr = circ_cross_corr / np.max(circ_cross_corr)\n",
      "/pfs/stor10/users/home/a/arvidh/Documents/perceived-route-complexity/alignment.py:74: RuntimeWarning: invalid value encountered in divide\n",
      "  normalized_circ_cross_corr = circ_cross_corr / np.max(circ_cross_corr)\n",
      "/pfs/stor10/users/home/a/arvidh/Documents/perceived-route-complexity/alignment.py:74: RuntimeWarning: divide by zero encountered in divide\n",
      "  normalized_circ_cross_corr = circ_cross_corr / np.max(circ_cross_corr)\n",
      "/pfs/stor10/users/home/a/arvidh/Documents/perceived-route-complexity/alignment.py:74: RuntimeWarning: invalid value encountered in divide\n",
      "  normalized_circ_cross_corr = circ_cross_corr / np.max(circ_cross_corr)\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Failed finding OD_pairs for  graph: /proj/nobackup/streetnetwork-alignment/2025-03-A/local_origin_graphs/Cape Town_34996614.graphml error unclosed token: line 239835, column 2\n",
      "Finished finding OD_pairs for graph: Denver node: 176081390\n",
      "Finished finding OD_pairs for graph: Cape Town node: 266715705\n",
      "Finished finding OD_pairs for graph: Dubai node: 3151490641\n",
      "Failed finding OD_pairs for  graph: /proj/nobackup/streetnetwork-alignment/2025-03-A/local_origin_graphs/Bangkok_5919687081.graphml error unclosed token: line 160139, column 2\n",
      "Finished finding OD_pairs for graph: Denver node: 4436004856\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "/pfs/stor10/users/home/a/arvidh/Documents/perceived-route-complexity/alignment.py:74: RuntimeWarning: divide by zero encountered in divide\n",
      "  normalized_circ_cross_corr = circ_cross_corr / np.max(circ_cross_corr)\n",
      "/pfs/stor10/users/home/a/arvidh/Documents/perceived-route-complexity/alignment.py:74: RuntimeWarning: invalid value encountered in divide\n",
      "  normalized_circ_cross_corr = circ_cross_corr / np.max(circ_cross_corr)\n",
      "/pfs/stor10/users/home/a/arvidh/Documents/perceived-route-complexity/alignment.py:74: RuntimeWarning: divide by zero encountered in divide\n",
      "  normalized_circ_cross_corr = circ_cross_corr / np.max(circ_cross_corr)\n",
      "/pfs/stor10/users/home/a/arvidh/Documents/perceived-route-complexity/alignment.py:74: RuntimeWarning: invalid value encountered in divide\n",
      "  normalized_circ_cross_corr = circ_cross_corr / np.max(circ_cross_corr)\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Failed finding OD_pairs for  graph: /proj/nobackup/streetnetwork-alignment/2025-03-A/local_origin_graphs/Damascus_49355838.graphml error 'origin_graph' object has no attribute 'od_pairs'\n",
      "Finished finding OD_pairs for graph: Detroit node: 5052743506\n",
      "Finished finding OD_pairs for graph: Beijing node: 8100695142\n",
      "Finished finding OD_pairs for graph: Dublin node: 244062730\n",
      "Failed finding OD_pairs for  graph: /proj/nobackup/streetnetwork-alignment/2025-03-A/local_origin_graphs/Cairo_6660416815.graphml error no element found: line 669454, column 459\n",
      "Finished finding OD_pairs for graph: Detroit node: 62815449\n",
      "Failed finding OD_pairs for  graph: /proj/nobackup/streetnetwork-alignment/2025-03-A/local_origin_graphs/Boston_61369399.graphml error no element found: line 1, column 0\n",
      "Finished finding OD_pairs for graph: Denver node: 176096390\n",
      "Finished finding OD_pairs for graph: Beijing node: 8571957386\n",
      "Finished finding OD_pairs for graph: Dublin node: 1426962142\n",
      "Finished finding OD_pairs for graph: Berlin node: 30815443\n",
      "Finished finding OD_pairs for graph: Havana node: 456882944\n",
      "Finished finding OD_pairs for graph: Atlanta node: 69162374\n",
      "Finished finding OD_pairs for graph: Hong Kong node: 671852049\n",
      "Finished finding OD_pairs for graph: Houston node: 153228794\n",
      "Finished finding OD_pairs for graph: Dallas node: 5046916162\n",
      "Finished finding OD_pairs for graph: Johannesburg node: 344868352\n",
      "Finished finding OD_pairs for graph: Caracas node: 4880519633\n",
      "Finished finding OD_pairs for graph: Glasgow node: 257410306\n",
      "Finished finding OD_pairs for graph: Atlanta node: 69475361\n",
      "Finished finding OD_pairs for graph: Hanoi node: 6321980845\n",
      "Finished finding OD_pairs for graph: Atlanta node: 69427859\n",
      "Finished finding OD_pairs for graph: Kiev node: 314510463\n",
      "Finished finding OD_pairs for graph: Madrid node: 306213043\n",
      "Finished finding OD_pairs for graph: Dallas node: 81859176\n",
      "Finished finding OD_pairs for graph: Lima node: 475477875\n",
      "Finished finding OD_pairs for graph: Barcelona node: 601147833\n",
      "Finished finding OD_pairs for graph: Havana node: 673030929\n",
      "Finished finding OD_pairs for graph: Lisbon node: 3144812770\n",
      "Failed finding OD_pairs for  graph: /proj/nobackup/streetnetwork-alignment/2025-03-A/local_origin_graphs/Jerusalem_4346365799.graphml error 'NoneType' object has no attribute 'to_json'\n",
      "Failed finding OD_pairs for  graph: /proj/nobackup/streetnetwork-alignment/2025-03-A/local_origin_graphs/Manila_2461227007.graphml error 'NoneType' object has no attribute 'to_json'\n",
      "Finished finding OD_pairs for graph: Cleveland node: 931865882\n",
      "Finished finding OD_pairs for graph: Helsinki node: 62651791\n",
      "Finished finding OD_pairs for graph: Lima node: 847515129\n",
      "Finished finding OD_pairs for graph: Charlotte node: 172719801\n",
      "Finished finding OD_pairs for graph: Istanbul node: 2381987201\n",
      "Finished finding OD_pairs for graph: Dallas node: 7528196911\n",
      "Finished finding OD_pairs for graph: Jerusalem node: 1550815940\n",
      "Finished finding OD_pairs for graph: Melbourne node: 264829875\n",
      "Finished finding OD_pairs for graph: Berlin node: 28253316\n",
      "Finished finding OD_pairs for graph: Helsinki node: 5929326245\n",
      "Finished finding OD_pairs for graph: Manila node: 103801259\n",
      "Finished finding OD_pairs for graph: Baltimore node: 49524262\n",
      "Failed finding OD_pairs for  graph: /proj/nobackup/streetnetwork-alignment/2025-03-A/local_origin_graphs/Houston_152365466.graphml error unclosed token: line 145214, column 0\n",
      "Failed finding OD_pairs for  graph: /proj/nobackup/streetnetwork-alignment/2025-03-A/local_origin_graphs/Houston_1119643919.graphml error no element found: line 254512, column 2\n",
      "Finished finding OD_pairs for graph: Istanbul node: 1058892524\n",
      "Finished finding OD_pairs for graph: Chicago node: 261179911\n",
      "Failed finding OD_pairs for  graph: /proj/nobackup/streetnetwork-alignment/2025-03-A/local_origin_graphs/Kyoto_2054207965.graphml error 'origin_graph' object has no attribute 'od_pairs'\n",
      "Finished finding OD_pairs for graph: Nairobi node: 8478048514\n",
      "Failed finding OD_pairs for  graph: /proj/nobackup/streetnetwork-alignment/2025-03-A/local_origin_graphs/Montreal_264550399.graphml error 'NoneType' object has no attribute 'to_json'\n",
      "Failed finding OD_pairs for  graph: /proj/nobackup/streetnetwork-alignment/2025-03-A/local_origin_graphs/New Orleans_5758348319.graphml error 'NoneType' object has no attribute 'to_json'\n",
      "Finished finding OD_pairs for graph: Budapest node: 8199080326\n",
      "Finished finding OD_pairs for graph: Jakarta node: 342828282\n",
      "Finished finding OD_pairs for graph: Amsterdam node: 4004330717\n",
      "Finished finding OD_pairs for graph: Kyoto node: 1323463826\n",
      "Finished finding OD_pairs for graph: Chicago node: 709393461\n",
      "Finished finding OD_pairs for graph: Istanbul node: 910813094\n",
      "Failed finding OD_pairs for  graph: /proj/nobackup/streetnetwork-alignment/2025-03-A/local_origin_graphs/Los Angeles_1784125340.graphml error 'NoneType' object has no attribute 'to_json'\n",
      "Failed finding OD_pairs for  graph: /proj/nobackup/streetnetwork-alignment/2025-03-A/local_origin_graphs/Nairobi_2647301183.graphml error 'NoneType' object has no attribute 'to_json'\n",
      "Finished finding OD_pairs for graph: Baltimore node: 49475152\n",
      "Finished finding OD_pairs for graph: Kyoto node: 2384229646\n",
      "Finished finding OD_pairs for graph: Copenhagen node: 25914919\n",
      "Finished finding OD_pairs for graph: Johannesburg node: 247764898\n",
      "Finished finding OD_pairs for graph: Munich node: 26057149\n",
      "Finished finding OD_pairs for graph: Rio de Janeiro node: 3196289051\n",
      "Finished finding OD_pairs for graph: Amsterdam node: 6466683449\n",
      "Finished finding OD_pairs for graph: Havana node: 1428183619\n",
      "Finished finding OD_pairs for graph: Mexico City node: 506670026\n",
      "Failed finding OD_pairs for  graph: /proj/nobackup/streetnetwork-alignment/2025-03-A/local_origin_graphs/Mexico City_6145696406.graphml error 'NoneType' object has no attribute 'to_json'\n",
      "Failed finding OD_pairs for  graph: /proj/nobackup/streetnetwork-alignment/2025-03-A/local_origin_graphs/Stockholm_300028317.graphml error 'NoneType' object has no attribute 'to_json'\n",
      "Finished finding OD_pairs for graph: Buenos Aires node: 196253122\n",
      "Finished finding OD_pairs for graph: Hanoi node: 6624722028\n",
      "Finished finding OD_pairs for graph: Minneapolis node: 6105944731\n",
      "Finished finding OD_pairs for graph: Pyongyang node: 10913165184\n",
      "Finished finding OD_pairs for graph: Stockholm node: 10069467049\n",
      "Finished finding OD_pairs for graph: Bogota node: 455338156\n",
      "Finished finding OD_pairs for graph: Miami node: 99231136\n",
      "Finished finding OD_pairs for graph: Phnom Penh node: 3031220435\n",
      "Finished finding OD_pairs for graph: Charlotte node: 172645493\n",
      "Finished finding OD_pairs for graph: Karachi node: 6752563341\n",
      "Finished finding OD_pairs for graph: Damascus node: 49234020\n",
      "Finished finding OD_pairs for graph: Dublin node: 985552726\n",
      "Finished finding OD_pairs for graph: Manila node: 246784701\n",
      "Finished finding OD_pairs for graph: Seattle node: 2578551196\n",
      "Finished finding OD_pairs for graph: Buenos Aires node: 321124100\n",
      "Finished finding OD_pairs for graph: Mexico City node: 5269283797\n",
      "Finished finding OD_pairs for graph: Cape Town node: 1028937309\n",
      "Finished finding OD_pairs for graph: Lagos node: 1656710790\n",
      "Finished finding OD_pairs for graph: Melbourne node: 319702107\n",
      "Finished finding OD_pairs for graph: Munich node: 151222692\n",
      "Finished finding OD_pairs for graph: Rio de Janeiro node: 551678811\n",
      "Failed finding OD_pairs for  graph: /proj/nobackup/streetnetwork-alignment/2025-03-A/local_origin_graphs/Los Angeles_122991507.graphml error 'NoneType' object has no attribute 'to_json'\n",
      "Failed finding OD_pairs for  graph: /proj/nobackup/streetnetwork-alignment/2025-03-A/local_origin_graphs/Paris_9995237006.graphml error 'NoneType' object has no attribute 'to_json'\n",
      "Failed finding OD_pairs for  graph: /proj/nobackup/streetnetwork-alignment/2025-03-A/local_origin_graphs/Taipei_2197211193.graphml error 'NoneType' object has no attribute 'to_json'\n",
      "Finished finding OD_pairs for graph: Boston node: 71947932\n",
      "Finished finding OD_pairs for graph: Melbourne node: 2206496434\n",
      "Finished finding OD_pairs for graph: Rio de Janeiro node: 2598645635\n",
      "Finished finding OD_pairs for graph: Casablanca node: 10739449140\n",
      "Finished finding OD_pairs for graph: Madrid node: 4894003636\n",
      "Finished finding OD_pairs for graph: Munich node: 193855679\n",
      "Finished finding OD_pairs for graph: Portland node: 40507012\n",
      "Failed finding OD_pairs for  graph: /proj/nobackup/streetnetwork-alignment/2025-03-A/local_origin_graphs/Phoenix_1526052706.graphml error 'NoneType' object has no attribute 'to_json'\n",
      "Failed finding OD_pairs for  graph: /proj/nobackup/streetnetwork-alignment/2025-03-A/local_origin_graphs/Toronto_411926670.graphml error 'NoneType' object has no attribute 'to_json'\n",
      "Failed finding OD_pairs for  graph: /proj/nobackup/streetnetwork-alignment/2025-03-A/local_origin_graphs/Lisbon_672690524.graphml error 'NoneType' object has no attribute 'to_json'\n",
      "Failed finding OD_pairs for  graph: /proj/nobackup/streetnetwork-alignment/2025-03-A/local_origin_graphs/Paris_237709807.graphml error 'NoneType' object has no attribute 'to_json'\n",
      "Failed finding OD_pairs for  graph: /proj/nobackup/streetnetwork-alignment/2025-03-A/local_origin_graphs/St Louis_53170740.graphml error 'NoneType' object has no attribute 'to_json'\n",
      "Failed finding OD_pairs for  graph: /proj/nobackup/streetnetwork-alignment/2025-03-A/local_origin_graphs/Singapore_394498292.graphml error 'NoneType' object has no attribute 'to_json'\n",
      "Failed finding OD_pairs for  graph: /proj/nobackup/streetnetwork-alignment/2025-03-A/local_origin_graphs/Venice_30025166.graphml error 'NoneType' object has no attribute 'to_json'\n",
      "Finished finding OD_pairs for graph: Budapest node: 3445703817\n",
      "Finished finding OD_pairs for graph: Jakarta node: 6359768000\n",
      "Finished finding OD_pairs for graph: Rome node: 921200070\n",
      "Finished finding OD_pairs for graph: Taipei node: 2397313001\n",
      "Finished finding OD_pairs for graph: Caracas node: 1969824700\n",
      "Finished finding OD_pairs for graph: Glasgow node: 957116477\n",
      "Finished finding OD_pairs for graph: Miami node: 99138387\n",
      "Finished finding OD_pairs for graph: Prague node: 128772851\n",
      "Finished finding OD_pairs for graph: Stockholm node: 109688079\n",
      "Failed finding OD_pairs for  graph: /proj/nobackup/streetnetwork-alignment/2025-03-A/local_origin_graphs/Pittsburgh_9219651294.graphml error 'NoneType' object has no attribute 'to_json'\n",
      "Failed finding OD_pairs for  graph: /proj/nobackup/streetnetwork-alignment/2025-03-A/local_origin_graphs/Vienna_59991392.graphml error 'NoneType' object has no attribute 'to_json'\n",
      "Failed finding OD_pairs for  graph: /proj/nobackup/streetnetwork-alignment/2025-03-A/local_origin_graphs/Jakarta_1357936448.graphml error 'NoneType' object has no attribute 'to_json'\n",
      "Failed finding OD_pairs for  graph: /proj/nobackup/streetnetwork-alignment/2025-03-A/local_origin_graphs/Lagos_5439068818.graphml error 'NoneType' object has no attribute 'to_json'\n",
      "Failed finding OD_pairs for  graph: /proj/nobackup/streetnetwork-alignment/2025-03-A/local_origin_graphs/Moscow_305101467.graphml error 'NoneType' object has no attribute 'to_json'\n",
      "Failed finding OD_pairs for  graph: /proj/nobackup/streetnetwork-alignment/2025-03-A/local_origin_graphs/New Orleans_115605626.graphml error 'NoneType' object has no attribute 'to_json'\n",
      "Failed finding OD_pairs for  graph: /proj/nobackup/streetnetwork-alignment/2025-03-A/local_origin_graphs/San Francisco_65352679.graphml error 'NoneType' object has no attribute 'to_json'\n",
      "Failed finding OD_pairs for  graph: /proj/nobackup/streetnetwork-alignment/2025-03-A/local_origin_graphs/Warsaw_1250996553.graphml error 'NoneType' object has no attribute 'to_json'\n",
      "Failed finding OD_pairs for  graph: /proj/nobackup/streetnetwork-alignment/2025-03-A/local_origin_graphs/Venice_344058248.graphml error 'NoneType' object has no attribute 'to_json'\n",
      "Failed finding OD_pairs for  graph: /proj/nobackup/streetnetwork-alignment/2025-03-A/local_origin_graphs/Singapore_1795313962.graphml error 'NoneType' object has no attribute 'to_json'\n",
      "Failed finding OD_pairs for  graph: /proj/nobackup/streetnetwork-alignment/2025-03-A/local_origin_graphs/Venice_1081041933.graphml error 'NoneType' object has no attribute 'to_json'\n",
      "Failed finding OD_pairs for  graph: /proj/nobackup/streetnetwork-alignment/2025-03-A/local_origin_graphs/Pyongyang_8123978794.graphml error 'NoneType' object has no attribute 'to_json'\n",
      "Failed finding OD_pairs for  graph: /proj/nobackup/streetnetwork-alignment/2025-03-A/local_origin_graphs/St Louis_53165759.graphml error 'NoneType' object has no attribute 'to_json'\n",
      "Failed finding OD_pairs for  graph: /proj/nobackup/streetnetwork-alignment/2025-03-A/local_origin_graphs/Philadelphia_109859056.graphml error 'NoneType' object has no attribute 'to_json'\n",
      "Failed finding OD_pairs for  graph: /proj/nobackup/streetnetwork-alignment/2025-03-A/local_origin_graphs/Taipei_665103687.graphml error 'NoneType' object has no attribute 'to_json'\n",
      "Finished finding OD_pairs for graph: Bangkok node: 5912926024\n",
      "Finished finding OD_pairs for graph: Phnom Penh node: 8835223406\n",
      "Finished finding OD_pairs for graph: Sydney node: 5657629845\n",
      "Finished finding OD_pairs for graph: Budapest node: 283547419\n",
      "Finished finding OD_pairs for graph: Las Vegas node: 5478742567\n",
      "Finished finding OD_pairs for graph: Mumbai node: 1920266050\n",
      "Finished finding OD_pairs for graph: Portland node: 1246201804\n",
      "Finished finding OD_pairs for graph: Vancouver node: 637800686\n",
      "Failed finding OD_pairs for  graph: /proj/nobackup/streetnetwork-alignment/2025-03-A/local_origin_graphs/Philadelphia_110377701.graphml error 'NoneType' object has no attribute 'to_json'\n",
      "Failed finding OD_pairs for  graph: /proj/nobackup/streetnetwork-alignment/2025-03-A/local_origin_graphs/Toronto_97275649.graphml error 'NoneType' object has no attribute 'to_json'\n",
      "Failed finding OD_pairs for  graph: /proj/nobackup/streetnetwork-alignment/2025-03-A/local_origin_graphs/Pyongyang_10571642811.graphml error 'NoneType' object has no attribute 'to_json'\n",
      "Failed finding OD_pairs for  graph: /proj/nobackup/streetnetwork-alignment/2025-03-A/local_origin_graphs/Shanghai_623410210.graphml error 'NoneType' object has no attribute 'to_json'\n",
      "Failed finding OD_pairs for  graph: /proj/nobackup/streetnetwork-alignment/2025-03-A/local_origin_graphs/Vienna_306224291.graphml error 'NoneType' object has no attribute 'to_json'\n",
      "Finished finding OD_pairs for graph: Copenhagen node: 4886121133\n",
      "Finished finding OD_pairs for graph: Lisbon node: 310163544\n",
      "Finished finding OD_pairs for graph: Oslo node: 6952663445\n",
      "Finished finding OD_pairs for graph: Pittsburgh node: 105098273\n",
      "Finished finding OD_pairs for graph: Ulaanbaatar node: 8319217007\n",
      "Finished finding OD_pairs for graph: Casablanca node: 1885926363\n",
      "Finished finding OD_pairs for graph: Orlando node: 100698869\n",
      "Finished finding OD_pairs for graph: San Francisco node: 2802765555\n",
      "Finished finding OD_pairs for graph: Vienna node: 99109496\n",
      "Failed finding OD_pairs for  graph: /proj/nobackup/streetnetwork-alignment/2025-03-A/local_origin_graphs/Lima_4638564799.graphml error 'NoneType' object has no attribute 'to_json'\n",
      "Failed finding OD_pairs for  graph: /proj/nobackup/streetnetwork-alignment/2025-03-A/local_origin_graphs/Rome_1245515268.graphml error 'NoneType' object has no attribute 'to_json'\n",
      "Failed finding OD_pairs for  graph: /proj/nobackup/streetnetwork-alignment/2025-03-A/local_origin_graphs/Warsaw_273540421.graphml error 'NoneType' object has no attribute 'to_json'\n",
      "Finished finding OD_pairs for graph: Bogota node: 9415113905\n",
      "Finished finding OD_pairs for graph: Mumbai node: 7361627627\n",
      "Finished finding OD_pairs for graph: Pittsburgh node: 4046916268\n",
      "Finished finding OD_pairs for graph: Toronto node: 429565721\n",
      "Finished finding OD_pairs for graph: Cleveland node: 105588009\n",
      "Finished finding OD_pairs for graph: Hanoi node: 4893444842\n",
      "Finished finding OD_pairs for graph: Montreal node: 5194500927\n",
      "Finished finding OD_pairs for graph: Phoenix node: 41701305\n",
      "Finished finding OD_pairs for graph: Sydney node: 1819513130\n",
      "Failed finding OD_pairs for  graph: /proj/nobackup/streetnetwork-alignment/2025-03-A/local_origin_graphs/Shanghai_5344132393.graphml error 'NoneType' object has no attribute 'to_json'\n",
      "Failed finding OD_pairs for  graph: /proj/nobackup/streetnetwork-alignment/2025-03-A/local_origin_graphs/Vancouver_616471221.graphml error 'NoneType' object has no attribute 'to_json'\n",
      "Finished finding OD_pairs for graph: Bangkok node: 2964031639\n",
      "Finished finding OD_pairs for graph: Philadelphia node: 110299413\n",
      "Finished finding OD_pairs for graph: Singapore node: 4701889758\n",
      "Finished finding OD_pairs for graph: Warsaw node: 1747133057\n",
      "Failed finding OD_pairs for  graph: /proj/nobackup/streetnetwork-alignment/2025-03-A/local_origin_graphs/Minneapolis_33526130.graphml error 'NoneType' object has no attribute 'to_json'\n",
      "Failed finding OD_pairs for  graph: /proj/nobackup/streetnetwork-alignment/2025-03-A/local_origin_graphs/Phoenix_42284236.graphml error 'NoneType' object has no attribute 'to_json'\n",
      "Failed finding OD_pairs for  graph: /proj/nobackup/streetnetwork-alignment/2025-03-A/local_origin_graphs/Vancouver_332830207.graphml error 'NoneType' object has no attribute 'to_json'\n",
      "Finished finding OD_pairs for graph: Boston node: 73584404\n",
      "Finished finding OD_pairs for graph: Las Vegas node: 3639135095\n",
      "Finished finding OD_pairs for graph: Montreal node: 10979811030\n",
      "Finished finding OD_pairs for graph: Phnom Penh node: 10774027337\n",
      "Finished finding OD_pairs for graph: Ulaanbaatar node: 2942887925\n",
      "Failed finding OD_pairs for  graph: /proj/nobackup/streetnetwork-alignment/2025-03-A/local_origin_graphs/Ulaanbaatar_2098666288.graphml error 'NoneType' object has no attribute 'to_json'\n",
      "Failed finding OD_pairs for  graph: /proj/nobackup/streetnetwork-alignment/2025-03-A/local_origin_graphs/Manhattan_42798722.graphml error 'NoneType' object has no attribute 'to_json'\n",
      "Failed finding OD_pairs for  graph: /proj/nobackup/streetnetwork-alignment/2025-03-A/local_origin_graphs/Oslo_25313773.graphml error no element found: line 74538, column 189\n",
      "Failed finding OD_pairs for  graph: /proj/nobackup/streetnetwork-alignment/2025-03-A/local_origin_graphs/Paris_303861566.graphml error 'NoneType' object has no attribute 'to_json'\n",
      "Failed finding OD_pairs for  graph: /proj/nobackup/streetnetwork-alignment/2025-03-A/local_origin_graphs/Sydney_2543442368.graphml error 'NoneType' object has no attribute 'to_json'\n",
      "Finished finding OD_pairs for graph: Chicago node: 366310702\n",
      "Finished finding OD_pairs for graph: Kiev node: 1464034329\n",
      "Finished finding OD_pairs for graph: London node: 1664711671\n",
      "Finished finding OD_pairs for graph: Shanghai node: 8364473746\n",
      "Finished finding OD_pairs for graph: Washington node: 50186470\n",
      "Failed finding OD_pairs for  graph: /proj/nobackup/streetnetwork-alignment/2025-03-A/local_origin_graphs/London_2857779371.graphml error 'NoneType' object has no attribute 'to_json'\n",
      "Failed finding OD_pairs for  graph: /proj/nobackup/streetnetwork-alignment/2025-03-A/local_origin_graphs/St Louis_237094553.graphml error 'NoneType' object has no attribute 'to_json'\n",
      "Failed finding OD_pairs for  graph: /proj/nobackup/streetnetwork-alignment/2025-03-A/local_origin_graphs/Washington_2019253022.graphml error 'NoneType' object has no attribute 'to_json'\n",
      "Failed finding OD_pairs for  graph: /proj/nobackup/streetnetwork-alignment/2025-03-A/local_origin_graphs/Sao Paulo_2532735430.graphml error 'NoneType' object has no attribute 'to_json'\n",
      "Finished finding OD_pairs for graph: Charlotte node: 172325114\n",
      "Finished finding OD_pairs for graph: Karachi node: 6638794604\n",
      "Finished finding OD_pairs for graph: Amsterdam node: 46394761\n",
      "Finished finding OD_pairs for graph: Las Vegas node: 137438509\n",
      "Finished finding OD_pairs for graph: Mumbai node: 6490591813\n",
      "Finished finding OD_pairs for graph: Portland node: 40758069\n",
      "Finished finding OD_pairs for graph: Washington node: 1013396708\n",
      "Finished finding OD_pairs for graph: Baltimore node: 49379039\n",
      "Finished finding OD_pairs for graph: Kiev node: 1655807643\n",
      "Finished finding OD_pairs for graph: Los Angeles node: 1905090816\n",
      "Finished finding OD_pairs for graph: Orlando node: 583088887\n",
      "Finished finding OD_pairs for graph: Sao Paulo node: 3960685975\n",
      "Failed finding OD_pairs for  graph: /proj/nobackup/streetnetwork-alignment/2025-03-A/local_origin_graphs/Madrid_155512534.graphml error 'NoneType' object has no attribute 'to_json'\n",
      "Failed finding OD_pairs for  graph: /proj/nobackup/streetnetwork-alignment/2025-03-A/local_origin_graphs/Nairobi_7184874988.graphml error 'NoneType' object has no attribute 'to_json'\n",
      "Failed finding OD_pairs for  graph: /proj/nobackup/streetnetwork-alignment/2025-03-A/local_origin_graphs/Sarajevo_6997691850.graphml error 'NoneType' object has no attribute 'to_json'\n",
      "Failed finding OD_pairs for  graph: /proj/nobackup/streetnetwork-alignment/2025-03-A/local_origin_graphs/Seattle_53200828.graphml error 'NoneType' object has no attribute 'to_json'\n",
      "Failed finding OD_pairs for  graph: /proj/nobackup/streetnetwork-alignment/2025-03-A/local_origin_graphs/Tehran_8364239999.graphml error 'NoneType' object has no attribute 'to_json'\n",
      "Finished finding OD_pairs for graph: Barcelona node: 10182303354\n",
      "Finished finding OD_pairs for graph: Helsinki node: 2897786371\n",
      "Finished finding OD_pairs for graph: Manhattan node: 595813965\n",
      "Finished finding OD_pairs for graph: Orlando node: 99552075\n",
      "Finished finding OD_pairs for graph: San Francisco node: 65321017\n",
      "Finished finding OD_pairs for graph: Sao Paulo node: 907695053\n",
      "Finished finding OD_pairs for graph: Barcelona node: 1489873459\n",
      "Finished finding OD_pairs for graph: Karachi node: 2462807926\n",
      "Finished finding OD_pairs for graph: Cairo node: 6694847003\n",
      "Failed finding OD_pairs for  graph: /proj/nobackup/streetnetwork-alignment/2025-03-A/local_origin_graphs/Seattle_53090153.graphml error 'NoneType' object has no attribute 'to_json'\n",
      "Failed finding OD_pairs for  graph: /proj/nobackup/streetnetwork-alignment/2025-03-A/local_origin_graphs/Seoul_4588371189.graphml error 'NoneType' object has no attribute 'to_json'\n",
      "Failed finding OD_pairs for  graph: /proj/nobackup/streetnetwork-alignment/2025-03-A/local_origin_graphs/Seoul_4173391965.graphml error 'NoneType' object has no attribute 'to_json'\n",
      "Failed finding OD_pairs for  graph: /proj/nobackup/streetnetwork-alignment/2025-03-A/local_origin_graphs/Hong Kong_1280110595.graphml error 'NoneType' object has no attribute 'to_json'\n",
      "Failed finding OD_pairs for  graph: /proj/nobackup/streetnetwork-alignment/2025-03-A/local_origin_graphs/Lagos_4537851533.graphml error 'NoneType' object has no attribute 'to_json'\n",
      "Failed finding OD_pairs for  graph: /proj/nobackup/streetnetwork-alignment/2025-03-A/local_origin_graphs/New Delhi_9849583064.graphml error 'NoneType' object has no attribute 'to_json'\n",
      "Finished finding OD_pairs for graph: Bogota node: 6565417943\n",
      "Finished finding OD_pairs for graph: New Delhi node: 3738902433\n",
      "Failed finding OD_pairs for  graph: /proj/nobackup/streetnetwork-alignment/2025-03-A/local_origin_graphs/New Orleans_115985150.graphml error 'NoneType' object has no attribute 'to_json'\n",
      "Failed finding OD_pairs for  graph: /proj/nobackup/streetnetwork-alignment/2025-03-A/local_origin_graphs/Seoul_3809204268.graphml error 'NoneType' object has no attribute 'to_json'\n",
      "Finished finding OD_pairs for graph: Casablanca node: 4057334438\n",
      "Finished finding OD_pairs for graph: New Delhi node: 6013422146\n",
      "Finished finding OD_pairs for graph: Cairo node: 6442406394\n",
      "Failed finding OD_pairs for  graph: /proj/nobackup/streetnetwork-alignment/2025-03-A/local_origin_graphs/Miami_1793966290.graphml error 'NoneType' object has no attribute 'to_json'\n",
      "Failed finding OD_pairs for  graph: /proj/nobackup/streetnetwork-alignment/2025-03-A/local_origin_graphs/Rome_298573944.graphml error 'NoneType' object has no attribute 'to_json'\n",
      "Failed finding OD_pairs for  graph: /proj/nobackup/streetnetwork-alignment/2025-03-A/local_origin_graphs/Tokyo_1351313231.graphml error 'NoneType' object has no attribute 'to_json'\n",
      "Finished finding OD_pairs for graph: Caracas node: 6828018578\n",
      "Finished finding OD_pairs for graph: Glasgow node: 838877018\n",
      "Finished finding OD_pairs for graph: Minneapolis node: 34384558\n",
      "Finished finding OD_pairs for graph: Prague node: 5160729113\n",
      "Finished finding OD_pairs for graph: Tehran node: 7617292213\n",
      "Failed finding OD_pairs for  graph: /proj/nobackup/streetnetwork-alignment/2025-03-A/local_origin_graphs/Sarajevo_574872379.graphml error 'NoneType' object has no attribute 'to_json'\n",
      "Failed finding OD_pairs for  graph: /proj/nobackup/streetnetwork-alignment/2025-03-A/local_origin_graphs/Tehran_2078370535.graphml error 'NoneType' object has no attribute 'to_json'\n",
      "Finished finding OD_pairs for graph: Cleveland node: 3515152892\n",
      "Finished finding OD_pairs for graph: Hong Kong node: 3080352352\n",
      "Finished finding OD_pairs for graph: Jerusalem node: 492086203\n",
      "Finished finding OD_pairs for graph: Manhattan node: 106133540\n",
      "Finished finding OD_pairs for graph: Osaka node: 1791138937\n",
      "Failed finding OD_pairs for  graph: /proj/nobackup/streetnetwork-alignment/2025-03-A/local_origin_graphs/Moscow_12246782706.graphml error 'NoneType' object has no attribute 'to_json'\n",
      "Failed finding OD_pairs for  graph: /proj/nobackup/streetnetwork-alignment/2025-03-A/local_origin_graphs/Oslo_315858623.graphml error 'NoneType' object has no attribute 'to_json'\n",
      "Failed finding OD_pairs for  graph: /proj/nobackup/streetnetwork-alignment/2025-03-A/local_origin_graphs/Prague_11635463991.graphml error 'NoneType' object has no attribute 'to_json'\n",
      "Failed finding OD_pairs for  graph: /proj/nobackup/streetnetwork-alignment/2025-03-A/local_origin_graphs/Tokyo_763081550.graphml error 'NoneType' object has no attribute 'to_json'\n",
      "Finished finding OD_pairs for graph: Berlin node: 444562882\n",
      "Finished finding OD_pairs for graph: Johannesburg node: 7049631855\n",
      "Finished finding OD_pairs for graph: Moscow node: 9142514956\n",
      "Failed finding OD_pairs for  graph: /proj/nobackup/streetnetwork-alignment/2025-03-A/local_origin_graphs/Osaka_4898921732.graphml error no element found: line 1, column 0\n",
      "Finished finding OD_pairs for graph: Osaka node: 1610304222\n"
     ]
    },
    {
     "ename": "KeyError",
     "evalue": "'start_node'",
     "output_type": "error",
     "traceback": [
      "\u001b[0;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[0;31mKeyError\u001b[0m                                  Traceback (most recent call last)",
      "File \u001b[0;32m/hpc2n/eb/software/SciPy-bundle/2023.11-gfbf-2023b/lib/python3.11/site-packages/pandas/core/indexes/base.py:3790\u001b[0m, in \u001b[0;36mIndex.get_loc\u001b[0;34m(self, key)\u001b[0m\n\u001b[1;32m   3789\u001b[0m \u001b[38;5;28;01mtry\u001b[39;00m:\n\u001b[0;32m-> 3790\u001b[0m     \u001b[38;5;28;01mreturn\u001b[39;00m \u001b[38;5;28;43mself\u001b[39;49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43m_engine\u001b[49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mget_loc\u001b[49m\u001b[43m(\u001b[49m\u001b[43mcasted_key\u001b[49m\u001b[43m)\u001b[49m\n\u001b[1;32m   3791\u001b[0m \u001b[38;5;28;01mexcept\u001b[39;00m \u001b[38;5;167;01mKeyError\u001b[39;00m \u001b[38;5;28;01mas\u001b[39;00m err:\n",
      "File \u001b[0;32mindex.pyx:152\u001b[0m, in \u001b[0;36mpandas._libs.index.IndexEngine.get_loc\u001b[0;34m()\u001b[0m\n",
      "File \u001b[0;32mindex.pyx:181\u001b[0m, in \u001b[0;36mpandas._libs.index.IndexEngine.get_loc\u001b[0;34m()\u001b[0m\n",
      "File \u001b[0;32mpandas/_libs/hashtable_class_helper.pxi:7080\u001b[0m, in \u001b[0;36mpandas._libs.hashtable.PyObjectHashTable.get_item\u001b[0;34m()\u001b[0m\n",
      "File \u001b[0;32mpandas/_libs/hashtable_class_helper.pxi:7088\u001b[0m, in \u001b[0;36mpandas._libs.hashtable.PyObjectHashTable.get_item\u001b[0;34m()\u001b[0m\n",
      "\u001b[0;31mKeyError\u001b[0m: 'start_node'",
      "\nThe above exception was the direct cause of the following exception:\n",
      "\u001b[0;31mKeyError\u001b[0m                                  Traceback (most recent call last)",
      "Cell \u001b[0;32mIn[2], line 45\u001b[0m\n\u001b[1;32m     43\u001b[0m \u001b[38;5;28;01mfor\u001b[39;00m result \u001b[38;5;129;01min\u001b[39;00m results:\n\u001b[1;32m     44\u001b[0m     \u001b[38;5;28;01mif\u001b[39;00m result[\u001b[38;5;241m0\u001b[39m]:\n\u001b[0;32m---> 45\u001b[0m         mask \u001b[38;5;241m=\u001b[39m (df[\u001b[38;5;124m'\u001b[39m\u001b[38;5;124mcity_name\u001b[39m\u001b[38;5;124m'\u001b[39m] \u001b[38;5;241m==\u001b[39m result[\u001b[38;5;241m1\u001b[39m]) \u001b[38;5;241m&\u001b[39m (\u001b[43mdf\u001b[49m\u001b[43m[\u001b[49m\u001b[38;5;124;43m'\u001b[39;49m\u001b[38;5;124;43mstart_node\u001b[39;49m\u001b[38;5;124;43m'\u001b[39;49m\u001b[43m]\u001b[49m \u001b[38;5;241m==\u001b[39m result[\u001b[38;5;241m2\u001b[39m])\n\u001b[1;32m     46\u001b[0m         df\u001b[38;5;241m.\u001b[39mloc[mask, \u001b[38;5;124m'\u001b[39m\u001b[38;5;124mod_pairs_added\u001b[39m\u001b[38;5;124m'\u001b[39m] \u001b[38;5;241m=\u001b[39m \u001b[38;5;28;01mTrue\u001b[39;00m\n\u001b[1;32m     48\u001b[0m df\u001b[38;5;241m.\u001b[39mto_csv(city_sample_nodes_path)\n",
      "File \u001b[0;32m/hpc2n/eb/software/SciPy-bundle/2023.11-gfbf-2023b/lib/python3.11/site-packages/pandas/core/frame.py:3893\u001b[0m, in \u001b[0;36mDataFrame.__getitem__\u001b[0;34m(self, key)\u001b[0m\n\u001b[1;32m   3891\u001b[0m \u001b[38;5;28;01mif\u001b[39;00m \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39mcolumns\u001b[38;5;241m.\u001b[39mnlevels \u001b[38;5;241m>\u001b[39m \u001b[38;5;241m1\u001b[39m:\n\u001b[1;32m   3892\u001b[0m     \u001b[38;5;28;01mreturn\u001b[39;00m \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39m_getitem_multilevel(key)\n\u001b[0;32m-> 3893\u001b[0m indexer \u001b[38;5;241m=\u001b[39m \u001b[38;5;28;43mself\u001b[39;49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mcolumns\u001b[49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mget_loc\u001b[49m\u001b[43m(\u001b[49m\u001b[43mkey\u001b[49m\u001b[43m)\u001b[49m\n\u001b[1;32m   3894\u001b[0m \u001b[38;5;28;01mif\u001b[39;00m is_integer(indexer):\n\u001b[1;32m   3895\u001b[0m     indexer \u001b[38;5;241m=\u001b[39m [indexer]\n",
      "File \u001b[0;32m/hpc2n/eb/software/SciPy-bundle/2023.11-gfbf-2023b/lib/python3.11/site-packages/pandas/core/indexes/base.py:3797\u001b[0m, in \u001b[0;36mIndex.get_loc\u001b[0;34m(self, key)\u001b[0m\n\u001b[1;32m   3792\u001b[0m     \u001b[38;5;28;01mif\u001b[39;00m \u001b[38;5;28misinstance\u001b[39m(casted_key, \u001b[38;5;28mslice\u001b[39m) \u001b[38;5;129;01mor\u001b[39;00m (\n\u001b[1;32m   3793\u001b[0m         \u001b[38;5;28misinstance\u001b[39m(casted_key, abc\u001b[38;5;241m.\u001b[39mIterable)\n\u001b[1;32m   3794\u001b[0m         \u001b[38;5;129;01mand\u001b[39;00m \u001b[38;5;28many\u001b[39m(\u001b[38;5;28misinstance\u001b[39m(x, \u001b[38;5;28mslice\u001b[39m) \u001b[38;5;28;01mfor\u001b[39;00m x \u001b[38;5;129;01min\u001b[39;00m casted_key)\n\u001b[1;32m   3795\u001b[0m     ):\n\u001b[1;32m   3796\u001b[0m         \u001b[38;5;28;01mraise\u001b[39;00m InvalidIndexError(key)\n\u001b[0;32m-> 3797\u001b[0m     \u001b[38;5;28;01mraise\u001b[39;00m \u001b[38;5;167;01mKeyError\u001b[39;00m(key) \u001b[38;5;28;01mfrom\u001b[39;00m \u001b[38;5;21;01merr\u001b[39;00m\n\u001b[1;32m   3798\u001b[0m \u001b[38;5;28;01mexcept\u001b[39;00m \u001b[38;5;167;01mTypeError\u001b[39;00m:\n\u001b[1;32m   3799\u001b[0m     \u001b[38;5;66;03m# If we have a listlike key, _check_indexing_error will raise\u001b[39;00m\n\u001b[1;32m   3800\u001b[0m     \u001b[38;5;66;03m#  InvalidIndexError. Otherwise we fall through and re-raise\u001b[39;00m\n\u001b[1;32m   3801\u001b[0m     \u001b[38;5;66;03m#  the TypeError.\u001b[39;00m\n\u001b[1;32m   3802\u001b[0m     \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39m_check_indexing_error(key)\n",
      "\u001b[0;31mKeyError\u001b[0m: 'start_node'"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Finished finding OD_pairs for graph: Buenos Aires node: 206163511\n",
      "Finished finding OD_pairs for graph: London node: 31200012\n",
      "Finished finding OD_pairs for graph: Sarajevo node: 9572343913\n",
      "Finished finding OD_pairs for graph: Tokyo node: 1503780971\n"
     ]
    }
   ],
   "source": [
    "import pandas as pd # for reading the csv file\n",
    "import joblib # replacing multiprocessing with joblib\n",
    "from origin_graph import origin_graph\n",
    "df = pd.read_csv(city_sample_nodes_path)\n",
    "\n",
    "local_odpair_folder = os.path.join(base_path, \"od_pair_data\")\n",
    "print(f\"odpair data will be stored at {local_odpair_folder}\")\n",
    "os.makedirs(local_odpair_folder, exist_ok=True)\n",
    "\n",
    "\n",
    "if 'od_pairs_added' not in df.columns:\n",
    "    df['od_pairs_added'] = False\n",
    "\n",
    "\n",
    "def get_od_pairs(row):\n",
    "    try:\n",
    "        og = origin_graph.from_graphml(graphml_path=row['graph_path'])\n",
    "        og.create_od_pairs(min_radius=min_od_distance, max_radius=max_od_distance, sample_size=144)\n",
    "        od_pair_data = og.get_od_pair_data()\n",
    "        json_path = os.path.join(local_odpair_folder, f\"od_pair_{row['city_name']}_{row['node_id']}.json\")\n",
    "        od_pair_data.to_json(json_path, orient=\"records\", default_handler=str, indent=2)\n",
    "        print(f\"Finished finding OD_pairs for graph: {row['city_name']} node: {row['node_id']}\")\n",
    "        return True,row['city_name'],row['node_id']\n",
    "    except Exception as e:\n",
    "        print(f\"Failed finding OD_pairs for  graph: {row['graph_path']} error {e}\")\n",
    "        return False,row['city_name'],row['node_id']\n",
    "\n",
    "\n",
    "num_processes = (joblib.cpu_count() - 1)\n",
    "print(f\"Number of processes to use: {num_processes}\")\n",
    "\n",
    "\n",
    "\n",
    "rows_to_process = []\n",
    "for idx, row in df.iterrows():\n",
    "    if not row['od_pairs_added']:\n",
    "        rows_to_process.append(row)\n",
    "\n",
    "results = joblib.Parallel(n_jobs=num_processes, backend='loky')(\n",
    "    joblib.delayed(get_od_pairs)(row) for row in rows_to_process\n",
    ")\n",
    "\n",
    "for result in results:\n",
    "    if result[0]:\n",
    "        mask = (df['city_name'] == result[1]) & (df['start_node'] == result[2])\n",
    "        df.loc[mask, 'od_pairs_added'] = True\n",
    "\n",
    "df.to_csv(city_sample_nodes_path)\n",
    "    "
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {
    "jupyter": {
     "source_hidden": true
    }
   },
   "outputs": [],
   "source": [
    "import post_processing\n",
    "import pandas as pd\n",
    "od_pair_data = pd.read_json(\"example/origin_od_pairs.json\")\n",
    "\n",
    "od_pair_data = post_processing.label_length_outliers(od_pair_data)\n",
    "od_pair_data = post_processing.label_gridlike_groups(od_pair_data)\n",
    "\n",
    "# Before normalizing the complexity, we need to remove the length outliers.\n",
    "print(f\"od-pairs before removing length outliers {len(od_pair_data)}\")\n",
    "od_pair_data = od_pair_data[od_pair_data['length_outliers'] == False]\n",
    "print(f\"od-pairs after removing length outliers {len(od_pair_data)}\")\n",
    "od_pair_data = post_processing.normalize_complexity(od_pair_data)\n",
    "print(len(od_pair_data))\n",
    "# The od-pair data contains lists and dictionaries that are not easily saved to a csv file, so we store it as a json file.\n",
    "# Still, there some columns that need to be serialized to strings such as shapely polygon objects.\n",
    "od_pair_data.to_json(\"example/origin_od_pairs.json\",orient=\"records\",default_handler=str,indent=2)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "import matplotlib.pyplot as plt\n",
    "import pandas as pd\n",
    "\n",
    "od_pair_data = pd.read_json(\"example/origin_od_pairs.json\")\n",
    "\n",
    "\n",
    "od_pair_data['closest_strongest_lag'] = abs(od_pair_data['closest_strongest_lag'])\n",
    "\n",
    "od_pair_data = od_pair_data.sort_values(by=\"closest_strongest_lag\", ascending=True)\n",
    "\n",
    "\n",
    "city_counts = od_pair_data['city_name'].value_counts()\n",
    "city_counts.plot(kind='bar')\n",
    "plt.xlabel('City Name')\n",
    "plt.ylabel('Number of od-pairs')\n",
    "plt.title('Number of od-pairs in Each city')\n",
    "plt.show()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "osmnx201_venv",
   "language": "python",
   "name": "osmnx201_venv"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.11.5"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 4
}
